<Type Name="AsynchronousOperationException" FullName="System.IdentityModel.AsynchronousOperationException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="86f59d2512699984cc8e574db7281b2ff61da525" />
    <Meta Name="ms.sourcegitcommit" Value="c0c07dbd19cd7017243f9ac36915755f79bc8da6" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="it-IT" />
    <Meta Name="ms.lasthandoff" Value="11/27/2018" />
    <Meta Name="ms.locfileid" Value="52372251" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class AsynchronousOperationException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit AsynchronousOperationException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:System.IdentityModel.AsynchronousOperationException" />
  <TypeSignature Language="VB.NET" Value="Public Class AsynchronousOperationException&#xA;Inherits Exception" />
  <TypeSignature Language="C++ CLI" Value="public ref class AsynchronousOperationException : Exception" />
  <TypeSignature Language="F#" Value="type AsynchronousOperationException = class&#xA;    inherit Exception" />
  <AssemblyInfo>
    <AssemblyName>System.IdentityModel</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8">
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="3e81e-101">Eccezione generata quando si verifica un errore durante un'operazione asincrona.</span>
      <span class="sxs-lookup">
        <span data-stu-id="3e81e-101">The exception that is thrown when an error occurs during an asynchronous operation.</span>
      </span>
    </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="3e81e-102">Inizializza una nuova istanza della classe <see cref="T:System.IdentityModel.AsynchronousOperationException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-102">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="3e81e-103">Inizializza una nuova istanza della classe <see cref="T:System.IdentityModel.AsynchronousOperationException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-103">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="3e81e-104">Questo costruttore consente di inizializzare la proprietà <xref:System.Exception.Message> della nuova istanza in un messaggio di sistema in cui viene descritto l'errore.</span><span class="sxs-lookup"><span data-stu-id="3e81e-104">This constructor initializes the <xref:System.Exception.Message> property of the new instance to a system-supplied message that describes the error.</span></span> <span data-ttu-id="3e81e-105">Questo messaggio prende in considerazione le impostazioni cultura correnti del sistema.</span><span class="sxs-lookup"><span data-stu-id="3e81e-105">This message takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="3e81e-106">Nella tabella seguente mostra i valori iniziali delle proprietà per la nuova istanza.</span><span class="sxs-lookup"><span data-stu-id="3e81e-106">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="3e81e-107">Proprietà</span><span class="sxs-lookup"><span data-stu-id="3e81e-107">Property</span></span>|<span data-ttu-id="3e81e-108">Valore</span><span class="sxs-lookup"><span data-stu-id="3e81e-108">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="3e81e-109">`null`.</span><span class="sxs-lookup"><span data-stu-id="3e81e-109">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="3e81e-110">Stringa del messaggio di errore localizzato.</span><span class="sxs-lookup"><span data-stu-id="3e81e-110">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : Exception -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException innerException" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="innerException">
          <span data-ttu-id="3e81e-111">Eccezione <see cref="T:System.Exception" /> che rappresenta la causa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-111">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="3e81e-112">Se il parametro <paramref name="innerException" /> non è <see langword="null" />, l'eccezione corrente viene generata in un blocco <see langword="catch" /> in cui viene gestita l'eccezione interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-112">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="3e81e-113">Inizializza una nuova istanza della classe <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con un messaggio di errore fornito dal sistema e un riferimento all'eccezione interna che è la causa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-113">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a system-supplied error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="3e81e-114">Un'eccezione generata come risultato diretto di un'eccezione precedente deve includere un riferimento all'eccezione precedente nella proprietà <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="3e81e-114">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="3e81e-115">Il <xref:System.Exception.InnerException%2A> proprietà restituisce lo stesso valore passato nel costruttore.</span><span class="sxs-lookup"><span data-stu-id="3e81e-115">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="3e81e-116">Nella tabella seguente mostra i valori iniziali delle proprietà per la nuova istanza.</span><span class="sxs-lookup"><span data-stu-id="3e81e-116">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="3e81e-117">Proprietà</span><span class="sxs-lookup"><span data-stu-id="3e81e-117">Property</span></span>|<span data-ttu-id="3e81e-118">Valore</span><span class="sxs-lookup"><span data-stu-id="3e81e-118">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="3e81e-119">Riferimento all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="3e81e-119">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="3e81e-120">Un messaggio fornito dal sistema che descrive l'errore.</span><span class="sxs-lookup"><span data-stu-id="3e81e-120">A system-supplied message that describes the error.</span></span> <span data-ttu-id="3e81e-121">Questo messaggio prende in considerazione le impostazioni cultura correnti del sistema.</span><span class="sxs-lookup"><span data-stu-id="3e81e-121">This message takes into account the current system culture.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : string -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="3e81e-122">Messaggio di errore in cui viene indicato il motivo dell'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-122">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="3e81e-123">Inizializza una nuova istanza della classe <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con un messaggio di errore specificato.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-123">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a specified error message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="3e81e-124">Questo costruttore inizializza la <xref:System.Exception.Message%2A> proprietà della nuova eccezione utilizzando il `message` parametro.</span><span class="sxs-lookup"><span data-stu-id="3e81e-124">This constructor initializes the <xref:System.Exception.Message%2A> property of the new exception using the `message` parameter.</span></span> <span data-ttu-id="3e81e-125">Il contenuto di `message` deve essere facilmente comprensibile.</span><span class="sxs-lookup"><span data-stu-id="3e81e-125">The content of `message` is intended to be understood by humans.</span></span> <span data-ttu-id="3e81e-126">Il chiamante del costruttore deve garantire che la stringa sia stata localizzata in base alle impostazioni cultura correnti del sistema.</span><span class="sxs-lookup"><span data-stu-id="3e81e-126">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span></span>  
  
 <span data-ttu-id="3e81e-127">Nella tabella seguente mostra i valori iniziali delle proprietà per la nuova istanza.</span><span class="sxs-lookup"><span data-stu-id="3e81e-127">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="3e81e-128">Proprietà</span><span class="sxs-lookup"><span data-stu-id="3e81e-128">Property</span></span>|<span data-ttu-id="3e81e-129">Valore</span><span class="sxs-lookup"><span data-stu-id="3e81e-129">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="3e81e-130">`null`.</span><span class="sxs-lookup"><span data-stu-id="3e81e-130">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="3e81e-131">Stringa del messaggio di errore.</span><span class="sxs-lookup"><span data-stu-id="3e81e-131">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; AsynchronousOperationException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="3e81e-132">Oggetto <see cref="T:System.Runtime.Serialization.SerializationInfo" /> che contiene i dati serializzati dell'oggetto.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-132">A <see cref="T:System.Runtime.Serialization.SerializationInfo" /> object that holds the serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="3e81e-133">Oggetto <see cref="T:System.Runtime.Serialization.StreamingContext" /> che contiene le informazioni contestuali sull'origine o sulla destinazione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-133">A <see cref="T:System.Runtime.Serialization.StreamingContext" /> object that contains the contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="3e81e-134">Inizializza una nuova istanza della classe <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con dati serializzati.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-134">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with serialized data.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="3e81e-135">Questo costruttore viene chiamato durante la deserializzazione per ricostituire l'oggetto eccezione trasmesso su un flusso.</span><span class="sxs-lookup"><span data-stu-id="3e81e-135">This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : string * Exception -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="3e81e-136">Messaggio di errore in cui viene indicato il motivo dell'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-136">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="3e81e-137">Eccezione <see cref="T:System.Exception" /> che rappresenta la causa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-137">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="3e81e-138">Se il parametro <paramref name="innerException" /> non è <see langword="null" />, l'eccezione corrente viene generata in un blocco <see langword="catch" /> in cui viene gestita l'eccezione interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-138">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="3e81e-139">Inizializza una nuova istanza della classe <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con un messaggio di errore specificato e un riferimento all'eccezione interna che è la causa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="3e81e-139">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="3e81e-140">Un'eccezione generata come risultato diretto di un'eccezione precedente deve includere un riferimento all'eccezione precedente nella proprietà <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="3e81e-140">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="3e81e-141">Il <xref:System.Exception.InnerException%2A> proprietà restituisce lo stesso valore passato nel costruttore.</span><span class="sxs-lookup"><span data-stu-id="3e81e-141">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="3e81e-142">Nella tabella seguente mostra i valori iniziali delle proprietà per la nuova istanza.</span><span class="sxs-lookup"><span data-stu-id="3e81e-142">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="3e81e-143">Proprietà</span><span class="sxs-lookup"><span data-stu-id="3e81e-143">Property</span></span>|<span data-ttu-id="3e81e-144">Valore</span><span class="sxs-lookup"><span data-stu-id="3e81e-144">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="3e81e-145">Riferimento all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="3e81e-145">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="3e81e-146">Stringa del messaggio di errore.</span><span class="sxs-lookup"><span data-stu-id="3e81e-146">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>