<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="MappingException.xml" source-language="en-US" target-language="it-IT">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac597e63fb09096023c3ed598a5d2d05ec953bd12d6.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">97e63fb09096023c3ed598a5d2d05ec953bd12d6</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Data.MappingException">
          <source>The exception that is thrown when mapping related service requests fail.</source>
          <target state="translated">Eccezione generata in caso di errore delle richieste di servizio correlate al mapping.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Data.MappingException">
          <source>For more information about how to handle exceptions in your code, see <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated">Per ulteriori informazioni sulle modalità di gestione delle eccezioni nel codice, vedere <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" uid="T:System.Data.MappingException">
          <source>Initializes a new instance of <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph>.</source>
          <target state="translated">Inizializza una nuova istanza di <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Data.MappingException">
          <source>For more information about how to handle exceptions in your code, see <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated">Per ulteriori informazioni sulle modalità di gestione delle eccezioni nel codice, vedere <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" uid="M:System.Data.MappingException.#ctor">
          <source>Initializes a new instance of <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph>.</source>
          <target state="translated">Inizializza una nuova istanza di <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Data.MappingException.#ctor">
          <source>For more information about how to handle exceptions in your code, see <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated">Per ulteriori informazioni sulle modalità di gestione delle eccezioni nel codice, vedere <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.Data.MappingException.#ctor(System.String)">
          <source>The message that describes the error.</source>
          <target state="translated">Messaggio in cui viene descritto l'errore.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Data.MappingException.#ctor(System.String)">
          <source>Initializes a new instance of <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph> with a specialized error message.</source>
          <target state="translated">Inizializza una nuova istanza di <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph> con un messaggio di errore specifico.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Data.MappingException.#ctor(System.String)">
          <source>For more information about how to handle exceptions in your code, see <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated">Per ulteriori informazioni sulle modalità di gestione delle eccezioni nel codice, vedere <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.Data.MappingException.#ctor(System.String,System.Exception)">
          <source>The message that describes the error.</source>
          <target state="translated">Messaggio in cui viene descritto l'errore.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Data.MappingException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception, or a null reference (<ph id="ph1">&lt;see langword="Nothing" /&gt;</ph> in Visual Basic) if no inner exception is specified.</source>
          <target state="translated">Eccezione causa dell'eccezione corrente o riferimento Null (<ph id="ph1">&lt;see langword="Nothing" /&gt;</ph> in Visual Basic) se non viene specificata alcuna eccezione interna.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Data.MappingException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph> that uses a specified error message and a reference to the inner exception.</source>
          <target state="translated">Inizializza una nuova istanza di <ph id="ph1">&lt;see cref="T:System.Data.MappingException" /&gt;</ph> che utilizza un messaggio di errore specifico e un riferimento all'eccezione interna.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Data.MappingException.#ctor(System.String,System.Exception)">
          <source>For more information about how to handle exceptions in your code, see <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated">Per ulteriori informazioni sulle modalità di gestione delle eccezioni nel codice, vedere <ph id="ph1">&lt;xref:System.Exception&gt;</ph>.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>