<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="UnhandledExceptionAction.xml" source-language="en-US" target-language="it-IT">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5070ae82d795d2b3a920f23bb6d8e67539cdf87c2.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">070ae82d795d2b3a920f23bb6d8e67539cdf87c2</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Activities.UnhandledExceptionAction">
          <source>Specifies the action that occurs when an exception escapes the root of a workflow.</source>
          <target state="translated">Specifica l'azione che si verifica quando un'eccezione esegue l'escape della radice di un flusso di lavoro.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> function is invoked if an exception escapes the root of the workflow.</source>
          <target state="translated">La funzione <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> viene richiamata se un'eccezione esegue l'escape della radice del flusso di lavoro.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> provides access to the exception as well as a pointer to the <ph id="ph2">&lt;xref:System.Activities.Activity&gt;</ph> that generated the exception.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> fornisce accesso all'eccezione così come un puntatore al <ph id="ph2">&lt;xref:System.Activities.Activity&gt;</ph> che ha generato l'eccezione.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>Terminate is the default action if no <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is specified.</source>
          <target state="translated">Terminare è l'azione predefinita se non <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> gestore viene specificato.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">Nell'esempio seguente viene richiamato un flusso di lavoro che genera un'eccezione.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">L'eccezione non viene gestita dal flusso di lavoro e viene richiamato il gestore <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is terminated.</source>
          <target state="translated">Gli argomenti <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> vengono controllati per fornire informazioni sull'eccezione e il flusso di lavoro viene terminato.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>Specifies that the <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> should abort the workflow.</source>
          <target state="translated">Specifica che <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> deve interrompere il flusso di lavoro.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>This results in <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Aborted%2A&gt;</ph> being called when the abort process is complete.</source>
          <target state="translated">Questo comporta <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Aborted%2A&gt;</ph> che è chiamato quando il processo di interruzione è completo.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The unhandled exception is used as the abort reason.</source>
          <target state="translated">L'eccezione non gestita viene utilizzata come motivo di interruzione.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">Nell'esempio seguente viene richiamato un flusso di lavoro che genera un'eccezione.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">L'eccezione non viene gestita dal flusso di lavoro e viene richiamato il gestore <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is aborted.</source>
          <target state="translated">Gli argomenti <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> vengono controllati per fornire informazioni sull'eccezione e il flusso di lavoro viene interrotto.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>Specifies that the <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> should schedule the cancellation of the root activity and resume execution.</source>
          <target state="translated">Specifica che <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> deve pianificare l'annullamento dell'attività radice e riprendere l'esecuzione.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>This results in <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph> being called when the cancellation process is complete.</source>
          <target state="translated">Questo comporta la chiamata di <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph> quando il processo di annullamento è completo.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">Nell'esempio seguente viene richiamato un flusso di lavoro che genera un'eccezione.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">L'eccezione non viene gestita dal flusso di lavoro e viene richiamato il gestore <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is cancelled.</source>
          <target state="translated">Gli argomenti <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> vengono controllati per fornire informazioni sull'eccezione e il flusso di lavoro viene annullato.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>Specifies that the <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> should schedule termination of the root activity and resume execution.</source>
          <target state="translated">Specifica che <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> deve pianificare la chiusura dell'attività radice e riprendere l'esecuzione.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>This results in <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph> being called when the termination process is complete.</source>
          <target state="translated">Questo comporta <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph> che è chiamato quando il processo di chiusura è completo.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The unhandled exception is used as the termination reason.</source>
          <target state="translated">L'eccezione non gestita viene utilizzata come motivo di interruzione.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>Terminate is the default action if no <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is specified.</source>
          <target state="translated">Terminare è l'azione predefinita se non <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> gestore viene specificato.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">Nell'esempio seguente viene richiamato un flusso di lavoro che genera un'eccezione.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">L'eccezione non viene gestita dal flusso di lavoro e viene richiamato il gestore <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is terminated.</source>
          <target state="translated">Gli argomenti <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> vengono controllati per fornire informazioni sull'eccezione e il flusso di lavoro viene terminato.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>