<Type Name="LinqDataSourceValidationException" FullName="System.Web.UI.WebControls.LinqDataSourceValidationException">
  <TypeSignature Language="C#" Value="public class LinqDataSourceValidationException : Exception, System.Web.DynamicData.IDynamicValidatorException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit LinqDataSourceValidationException extends System.Exception implements class System.Runtime.Serialization.ISerializable, class System.Web.DynamicData.IDynamicValidatorException" />
  <TypeSignature Language="DocId" Value="T:System.Web.UI.WebControls.LinqDataSourceValidationException" />
  <TypeSignature Language="VB.NET" Value="Public Class LinqDataSourceValidationException&#xA;Inherits Exception&#xA;Implements IDynamicValidatorException" />
  <TypeSignature Language="C++ CLI" Value="public ref class LinqDataSourceValidationException : Exception, System::Web::DynamicData::IDynamicValidatorException" />
  <AssemblyInfo>
    <AssemblyName>System.Web.Extensions</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces>
    <Interface>
      <InterfaceName>System.Web.DynamicData.IDynamicValidatorException</InterfaceName>
    </Interface>
  </Interfaces>
  <Docs>
    <summary><span data-ttu-id="dce14-101">Descrive un'eccezione verificatasi durante la convalida di valori nuovi o modificati prima che essi vengano inseriti, aggiornati o eliminati da un controllo <see cref="T:System.Web.UI.WebControls.LinqDataSource" />.</span><span class="sxs-lookup"><span data-stu-id="dce14-101">Describes an exception that occurred during validation of new or modified values before values are inserted, updated, or deleted by a <see cref="T:System.Web.UI.WebControls.LinqDataSource" /> control.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-102">La <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> classe contiene le eccezioni setter conversione e la proprietà di tipo.</span><span class="sxs-lookup"><span data-stu-id="dce14-102">The <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> class contains type conversion and property setter exceptions.</span></span> <span data-ttu-id="dce14-103">Tutte le eccezioni generate durante la convalida sono contenute nel <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> insieme.</span><span class="sxs-lookup"><span data-stu-id="dce14-103">All of the exceptions that are thrown during validation are contained in the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> collection.</span></span> <span data-ttu-id="dce14-104">È possibile recuperare ogni eccezione di convalida scorrendo la <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> insieme.</span><span class="sxs-lookup"><span data-stu-id="dce14-104">You can retrieve each validation exception by iterating through the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> collection.</span></span>  
  
 <span data-ttu-id="dce14-105">In genere si gestiscono le eccezioni nel <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, e <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> eventi.</span><span class="sxs-lookup"><span data-stu-id="dce14-105">You typically handle exceptions in the <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, and <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> events.</span></span> <span data-ttu-id="dce14-106">Se viene generata un'eccezione di convalida, il `Exception` proprietà del <xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs>, <xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs>, o <xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs> oggetto contiene un <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> oggetto.</span><span class="sxs-lookup"><span data-stu-id="dce14-106">If a validation exception is thrown, the `Exception` property of the <xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs>, <xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs>, or <xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs> object contains a <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> object.</span></span> <span data-ttu-id="dce14-107">Se viene generata alcuna eccezione, il `Exception` contiene proprietà `null`.</span><span class="sxs-lookup"><span data-stu-id="dce14-107">If no exception is thrown, the `Exception` property contains `null`.</span></span>  
  
 <span data-ttu-id="dce14-108">Per gestire le eccezioni di convalida, creare un gestore per il <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, o <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> evento.</span><span class="sxs-lookup"><span data-stu-id="dce14-108">To handle validation exceptions, create a handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, or <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> event.</span></span> <span data-ttu-id="dce14-109">Nel gestore eventi, controllare se il `Exception` l'argomento di classe di evento contiene un valore diverso da `null`.</span><span class="sxs-lookup"><span data-stu-id="dce14-109">In the event handler, check whether the `Exception` property of the event argument class contains a value other than `null`.</span></span> <span data-ttu-id="dce14-110">Se il `Exception` proprietà non è null e sono state generate eccezioni di convalida di uno o più, è possibile recuperare ogni eccezione di convalida nel <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> proprietà.</span><span class="sxs-lookup"><span data-stu-id="dce14-110">If the `Exception` property is not null, one or more validation exceptions were thrown and you can retrieve each validation exception in the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> property.</span></span>  
  
 <span data-ttu-id="dce14-111">Un'eccezione di convalida può verificarsi se un valore non corrisponde al tipo della proprietà.</span><span class="sxs-lookup"><span data-stu-id="dce14-111">A validation exception can occur if a value does not match the type of the property.</span></span> <span data-ttu-id="dce14-112">Ad esempio, il tentativo di aggiornare una proprietà integer usando caratteri non numerici causa un'eccezione di convalida.</span><span class="sxs-lookup"><span data-stu-id="dce14-112">For example, trying to update an integer property by using non-numeric characters causes a validation exception.</span></span> <span data-ttu-id="dce14-113">Una classe LINQ to SQL può contenere anche i criteri di convalida personalizzato che assicurarsi che la proprietà contiene un valore che si trova all'interno di un intervallo o modello previsto.</span><span class="sxs-lookup"><span data-stu-id="dce14-113">A LINQ to SQL class can also contain customized validation criteria that make sure that the property contains a value that is within an expected range or pattern.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="dce14-114">Nell'esempio seguente viene illustrato un gestore eventi per il <xref:System.Web.UI.WebControls.LinqDataSource.Updating> evento.</span><span class="sxs-lookup"><span data-stu-id="dce14-114">The following example shows an event handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating> event.</span></span> <span data-ttu-id="dce14-115">Vengono visualizzati gli eventuali messaggi di eccezione di convalida utilizzando un <xref:System.Web.UI.WebControls.Label> controllo.</span><span class="sxs-lookup"><span data-stu-id="dce14-115">It displays any validation exception messages by using a <xref:System.Web.UI.WebControls.Label> control.</span></span>  
  
```vb  
Protected Sub LinqDataSource_Updating(ByVal sender As Object, _  
        ByVal e As LinqDataSourceUpdateEventArgs)  
    If (e.Exception IsNot Nothing) Then  
        For Each innerException As KeyValuePair(Of String, Exception) _  
               In e.Exception.InnerExceptions  
            Label1.Text &= innerException.Key & ": " & _  
                innerException.Value.Message & "<br />"  
        Next  
        e.ExceptionHandled = True  
    End If  
End Sub  
```  
  
```csharp  
protected void LinqDataSource_Updating(object sender,   
        LinqDataSourceUpdateEventArgs e)  
{  
    if (e.Exception != null)  
    {  
        foreach (KeyValuePair<string, Exception> innerException in   
             e.Exception.InnerExceptions)  
        {  
        Label1.Text += innerException.Key + ": " +   
            innerException.Value.Message + "<br />";  
        }  
        e.ExceptionHandled = true;  
    }  
}  
```  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="dce14-116">Inizializza una nuova istanza della classe <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" />.</span><span class="sxs-lookup"><span data-stu-id="dce14-116">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="dce14-117">Inizializza una nuova istanza della classe <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> con un messaggio fornito dal sistema in cui viene descritto l'errore.</span><span class="sxs-lookup"><span data-stu-id="dce14-117">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a system-supplied message that describes the error.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-118">Il messaggio fornito dal sistema che descrive l'errore prende in considerazione le impostazioni cultura correnti.</span><span class="sxs-lookup"><span data-stu-id="dce14-118">The system-supplied message that describes the error takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="dce14-119">Nella tabella riportata di seguito sono illustrati i valori iniziali delle proprietà per un'istanza della classe <xref:System.Web.UI.WebControls.LinqDataSourceValidationException>.</span><span class="sxs-lookup"><span data-stu-id="dce14-119">The following table shows the initial property values for an instance of the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> class.</span></span>  
  
|<span data-ttu-id="dce14-120">Proprietà</span><span class="sxs-lookup"><span data-stu-id="dce14-120">Property</span></span>|<span data-ttu-id="dce14-121">Valore</span><span class="sxs-lookup"><span data-stu-id="dce14-121">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="dce14-122">`null`.</span><span class="sxs-lookup"><span data-stu-id="dce14-122">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="dce14-123">Descrizione localizzata fornita dal sistema.</span><span class="sxs-lookup"><span data-stu-id="dce14-123">A system-supplied localized description.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="dce14-124">Messaggio in cui viene descritto l'errore.</span><span class="sxs-lookup"><span data-stu-id="dce14-124">The message that describes the error.</span></span></param>
        <summary><span data-ttu-id="dce14-125">Inizializza una nuova istanza della classe <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> con un messaggio specificato in cui viene descritto l'errore.</span><span class="sxs-lookup"><span data-stu-id="dce14-125">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a specified message that describes the error.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-126">Nella tabella riportata di seguito sono illustrati i valori iniziali delle proprietà per un'istanza della classe <xref:System.Web.UI.WebControls.LinqDataSourceValidationException>.</span><span class="sxs-lookup"><span data-stu-id="dce14-126">The following table shows the initial property values for an instance of the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> class.</span></span>  
  
|<span data-ttu-id="dce14-127">Proprietà</span><span class="sxs-lookup"><span data-stu-id="dce14-127">Property</span></span>|<span data-ttu-id="dce14-128">Valore</span><span class="sxs-lookup"><span data-stu-id="dce14-128">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="dce14-129">`null`.</span><span class="sxs-lookup"><span data-stu-id="dce14-129">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="dce14-130">Stringa del messaggio di errore specificata in `message`.</span><span class="sxs-lookup"><span data-stu-id="dce14-130">The error message string specified in `message`.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected LinqDataSourceValidationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; LinqDataSourceValidationException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="dce14-131">Oggetto che contiene i dati oggetto serializzati.</span><span class="sxs-lookup"><span data-stu-id="dce14-131">The object that holds the serialized object data.</span></span></param>
        <param name="context"><span data-ttu-id="dce14-132">Informazioni contestuali sull'origine o sulla destinazione.</span><span class="sxs-lookup"><span data-stu-id="dce14-132">Context information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="dce14-133">Inizializza una nuova istanza della classe <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> con dati serializzati.</span><span class="sxs-lookup"><span data-stu-id="dce14-133">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with serialized data.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-134">Questo costruttore viene chiamato durante la deserializzazione per ricostituire l'oggetto eccezione trasmesso in un flusso.</span><span class="sxs-lookup"><span data-stu-id="dce14-134">This constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException (string message, System.Collections.Generic.IDictionary&lt;string,Exception&gt; innerExceptions);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Collections.Generic.IDictionary`2&lt;string, class System.Exception&gt; innerExceptions) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerExceptions As IDictionary(Of String, Exception))" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException(System::String ^ message, System::Collections::Generic::IDictionary&lt;System::String ^, Exception ^&gt; ^ innerExceptions);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerExceptions" Type="System.Collections.Generic.IDictionary&lt;System.String,System.Exception&gt;" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="dce14-135">Messaggio in cui viene descritto l'errore.</span><span class="sxs-lookup"><span data-stu-id="dce14-135">The message that describes the error.</span></span></param>
        <param name="innerExceptions"><span data-ttu-id="dce14-136">Insieme di eccezioni della convalida.</span><span class="sxs-lookup"><span data-stu-id="dce14-136">The collection of validation exceptions.</span></span></param>
        <summary><span data-ttu-id="dce14-137">Inizializza una nuova istanza della classe <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> con un messaggio specificato che descrive l'errore e un insieme di riferimenti a eccezioni interne.</span><span class="sxs-lookup"><span data-stu-id="dce14-137">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a specified message that describes the error, and a collection of references to inner exceptions.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="dce14-138">Messaggio in cui viene descritto l'errore.</span><span class="sxs-lookup"><span data-stu-id="dce14-138">The message that describes the error.</span></span></param>
        <param name="innerException"><span data-ttu-id="dce14-139">Eccezione che ha determinato l'eccezione corrente.</span><span class="sxs-lookup"><span data-stu-id="dce14-139">The exception that is the cause of the current exception.</span></span></param>
        <summary><span data-ttu-id="dce14-140">Inizializza una nuova istanza della classe <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> con un messaggio di errore specificato e un riferimento all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="dce14-140">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a specified error message and a reference to the inner exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-141">In genere non si utilizzerà questo costruttore poiché le eccezioni di convalida sono archiviate nel <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> proprietà, non il <xref:System.Exception.InnerException%2A> proprietà.</span><span class="sxs-lookup"><span data-stu-id="dce14-141">You typically will not use this constructor because validation exceptions are stored in the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> property, not the <xref:System.Exception.InnerException%2A> property.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="GetObjectData">
      <MemberSignature Language="C#" Value="public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig virtual instance void GetObjectData(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Public Overrides Sub GetObjectData (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; override void GetObjectData(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>System.Security.SecurityCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Void</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="dce14-142">Oggetto che include i dati oggetto serializzati relativi all'eccezione generata.</span><span class="sxs-lookup"><span data-stu-id="dce14-142">The object that holds the serialized object data for the exception that is being thrown.</span></span></param>
        <param name="context"><span data-ttu-id="dce14-143">Informazioni contestuali sull'origine o sulla destinazione.</span><span class="sxs-lookup"><span data-stu-id="dce14-143">Context information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="dce14-144">Ottiene informazioni sull'eccezione e le aggiunge all'oggetto <see cref="T:System.Runtime.Serialization.SerializationInfo" />.</span><span class="sxs-lookup"><span data-stu-id="dce14-144">Gets information about the exception and adds it to the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> object.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-145">Il <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData%2A> metodo aggiunge informazioni sull'eccezione per il <xref:System.Runtime.Serialization.SerializationInfo> oggetto di destinazione per la serializzazione.</span><span class="sxs-lookup"><span data-stu-id="dce14-145">The <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData%2A> method adds information about the exception to the <xref:System.Runtime.Serialization.SerializationInfo> object that is targeted for serialization.</span></span> <span data-ttu-id="dce14-146">Durante la deserializzazione, l'eccezione viene ricostituita dal <xref:System.Runtime.Serialization.SerializationInfo> che viene trasmesso sul flusso.</span><span class="sxs-lookup"><span data-stu-id="dce14-146">During deserialization, the exception is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> that is transmitted over the stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="InnerExceptions">
      <MemberSignature Language="C#" Value="public System.Collections.Generic.IDictionary&lt;string,Exception&gt; InnerExceptions { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Collections.Generic.IDictionary`2&lt;string, class System.Exception&gt; InnerExceptions" />
      <MemberSignature Language="DocId" Value="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property InnerExceptions As IDictionary(Of String, Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property System::Collections::Generic::IDictionary&lt;System::String ^, Exception ^&gt; ^ InnerExceptions { System::Collections::Generic::IDictionary&lt;System::String ^, Exception ^&gt; ^ get(); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Web.DynamicData.IDynamicValidatorException.InnerExceptions</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Collections.Generic.IDictionary&lt;System.String,System.Exception&gt;</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="dce14-147">Ottiene una o più eccezioni verificatesi durante la convalida di dati nuovi o modificati.</span><span class="sxs-lookup"><span data-stu-id="dce14-147">Gets one or more exceptions that occurred when new or modified data was being validated.</span></span></summary>
        <value><span data-ttu-id="dce14-148">Insieme contenente le eccezioni.</span><span class="sxs-lookup"><span data-stu-id="dce14-148">A collection that contains the exceptions.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="dce14-149">Il <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> insieme contiene tutte le eccezioni di convalida che sono state generate durante la convalida dei dati prima dell'aggiornamento, inserimento o l'operazione di eliminazione.</span><span class="sxs-lookup"><span data-stu-id="dce14-149">The <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> collection contains all the validation exceptions that were thrown during data validation before an update, insert, or delete operation.</span></span> <span data-ttu-id="dce14-150">Un'eccezione di convalida può verificarsi se un valore non corrisponde al tipo della proprietà.</span><span class="sxs-lookup"><span data-stu-id="dce14-150">A validation exception can occur if a value does not match the type of the property.</span></span> <span data-ttu-id="dce14-151">Se si tenta di aggiornare una proprietà integer usando caratteri non numerici, ad esempio, viene generata un'eccezione di convalida.</span><span class="sxs-lookup"><span data-stu-id="dce14-151">For example, if you try to update an integer property by using non-numeric characters, a validation exception is thrown.</span></span> <span data-ttu-id="dce14-152">Una classe LINQ to SQL può contenere anche i criteri di convalida personalizzato che assicurarsi che la proprietà contiene un valore che si trova all'interno di un intervallo o modello previsto.</span><span class="sxs-lookup"><span data-stu-id="dce14-152">A LINQ to SQL class can also contain customized validation criteria that make sure that the property contains a value that is within an expected range or pattern.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="dce14-153">Nell'esempio seguente viene illustrato un gestore eventi per il <xref:System.Web.UI.WebControls.LinqDataSource.Updating> evento.</span><span class="sxs-lookup"><span data-stu-id="dce14-153">The following example shows an event handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating> event.</span></span> <span data-ttu-id="dce14-154">Vengono visualizzati gli eventuali messaggi di eccezione di convalida utilizzando un <xref:System.Web.UI.WebControls.Label> controllo.</span><span class="sxs-lookup"><span data-stu-id="dce14-154">It displays any validation exception messages by using a <xref:System.Web.UI.WebControls.Label> control.</span></span>  
  
```vb  
Protected Sub LinqDataSource_Updating(ByVal sender As Object, _  
        ByVal e As LinqDataSourceUpdateEventArgs)  
    If (e.Exception IsNot Nothing) Then  
        For Each innerException As KeyValuePair(Of String, Exception) _  
                In e.Exception.InnerExceptions  
          Label1.Text &= innerException.Key & ": " & _   
                  innerException.Value.Message & "<br />"  
        Next  
        e.ExceptionHandled = True  
    End If  
End Sub  
```  
  
```csharp  
protected void LinqDataSource_Updating(object sender,   
        LinqDataSourceUpdateEventArgs e)   
{  
    if (e.Exception != null)  
    {  
        foreach (KeyValuePair<string, Exception> innerException in   
            e.Exception.InnerExceptions)  
        {  
            Label1.Text += innerException.Key + ": " +   
                innerException.Message + "<br />";  
        }  
        e.ExceptionHandled = true;  
    }  
}  
```  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>