<Type Name="InvalidPipelineStoreException" FullName="System.AddIn.Hosting.InvalidPipelineStoreException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="9bbe4e4cfa38c1fd53c0b87c4aacce4d1e815312" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="it-IT" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class InvalidPipelineStoreException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit InvalidPipelineStoreException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:System.AddIn.Hosting.InvalidPipelineStoreException" />
  <TypeSignature Language="VB.NET" Value="Public Class InvalidPipelineStoreException&#xA;Inherits Exception" />
  <TypeSignature Language="C++ CLI" Value="public ref class InvalidPipelineStoreException : Exception" />
  <AssemblyInfo>
    <AssemblyName>System.AddIn</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="845f6-101">Eccezione generata quando la ricerca di una directory ha esito negativo e l'utente non è autorizzato ad accedere al percorso radice della pipeline o a un percorso del componente aggiuntivo.</span>
      <span class="sxs-lookup">
        <span data-stu-id="845f6-101">The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="845f6-102">A differenza dell'eccezione <xref:System.IO.DirectoryNotFoundException>, questa eccezione non fornisce alcuna informazione sul percorso.</span><span class="sxs-lookup"><span data-stu-id="845f6-102">Unlike <xref:System.IO.DirectoryNotFoundException>, this exception does not provide any path information.</span></span> <span data-ttu-id="845f6-103">Ciò impedisce a un utente malintenzionato di specificare intenzionalmente percorsi errati e di utilizzare le informazioni restituite dall'eccezione per determinare i percorsi effettivi.</span><span class="sxs-lookup"><span data-stu-id="845f6-103">This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.</span></span>  
  
 <span data-ttu-id="845f6-104">Questa eccezione viene generata dai metodi di individuazione seguenti che compilano e aggiornano l'archivio di componenti aggiuntivi e sulla pipeline: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, e <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.</span><span class="sxs-lookup"><span data-stu-id="845f6-104">This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, and <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="845f6-105">Inizializza una nuova istanza della classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-105">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public InvalidPipelineStoreException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; InvalidPipelineStoreException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="845f6-106">Inizializza una nuova istanza della classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-106">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public InvalidPipelineStoreException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; InvalidPipelineStoreException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="845f6-107">Descrizione dell'errore.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-107">A description of the error.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="845f6-108">Inizializza una nuova istanza della classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> con il messaggio specificato.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-108">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class with the specified message.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected InvalidPipelineStoreException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; InvalidPipelineStoreException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="845f6-109">Dati serializzati dell'oggetto.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-109">The serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="845f6-110">Informazioni contestuali relative ai dati dell'oggetto di origine o di destinazione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-110">The contextual information about the source or destination object data.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="845f6-111">Inizializza una nuova istanza della classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> con le informazioni sulla serializzazione e sul contesto di flusso.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-111">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class with serialization and streaming context information.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="845f6-112">Questo costruttore viene chiamato durante la deserializzazione per ricostituire l'oggetto eccezione trasmesso in un flusso.</span><span class="sxs-lookup"><span data-stu-id="845f6-112">This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream.</span></span> <span data-ttu-id="845f6-113">Per ulteriori informazioni, vedere [serializzazione XML e SOAP](~/docs/standard/serialization/xml-and-soap-serialization.md).</span><span class="sxs-lookup"><span data-stu-id="845f6-113">For more information, see [XML and SOAP Serialization](~/docs/standard/serialization/xml-and-soap-serialization.md).</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public InvalidPipelineStoreException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; InvalidPipelineStoreException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="845f6-114">Descrizione dell'errore.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-114">A description of the error.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="845f6-115">Eccezione che ha determinato l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-115">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="845f6-116">Se il parametro <c>innerException</c> non è un riferimento Null, l'eccezione corrente viene generata in un blocco catch che gestisce l'eccezione interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-116">If the <c>innerException</c> parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="845f6-117">Inizializza una nuova istanza della classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> con il messaggio specificato e un riferimento all'eccezione interna che è la causa dell'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="845f6-117">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class with the specified message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="845f6-118">Un'eccezione generata come risultato diretto di un'eccezione precedente deve includere un riferimento all'eccezione precedente nella proprietà <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="845f6-118">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="845f6-119">Il <xref:System.Exception.InnerException%2A> proprietà restituisce lo stesso valore passato al costruttore o un riferimento null se il <xref:System.Exception.InnerException%2A> proprietà non fornisce il valore di eccezione interna al costruttore.</span><span class="sxs-lookup"><span data-stu-id="845f6-119">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed to the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="845f6-120">Nella tabella riportata di seguito sono illustrati i valori iniziali delle proprietà per un'istanza della classe <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="845f6-120">The following table shows the initial property values for an instance of the <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> class.</span></span>  
  
|<span data-ttu-id="845f6-121">Proprietà</span><span class="sxs-lookup"><span data-stu-id="845f6-121">Property</span></span>|<span data-ttu-id="845f6-122">Valore</span><span class="sxs-lookup"><span data-stu-id="845f6-122">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="845f6-123">Riferimento all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="845f6-123">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="845f6-124">Stringa del messaggio di errore localizzato.</span><span class="sxs-lookup"><span data-stu-id="845f6-124">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>