<Type Name="DataGridViewDataErrorEventArgs" FullName="System.Windows.Forms.DataGridViewDataErrorEventArgs">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="a2b2aa5c8f0cb5e2a51d9c7fbf7c050859d7274d" />
    <Meta Name="ms.sourcegitcommit" Value="5a49536d99d2d0b54e4cb7280870903e043272df" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="it-IT" />
    <Meta Name="ms.lasthandoff" Value="07/03/2018" />
    <Meta Name="ms.locfileid" Value="37513306" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class DataGridViewDataErrorEventArgs : System.Windows.Forms.DataGridViewCellCancelEventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit DataGridViewDataErrorEventArgs extends System.Windows.Forms.DataGridViewCellCancelEventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Windows.Forms.DataGridViewDataErrorEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class DataGridViewDataErrorEventArgs&#xA;Inherits DataGridViewCellCancelEventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class DataGridViewDataErrorEventArgs : System::Windows::Forms::DataGridViewCellCancelEventArgs" />
  <TypeSignature Language="F#" Value="type DataGridViewDataErrorEventArgs = class&#xA;    inherit DataGridViewCellCancelEventArgs" />
  <AssemblyInfo>
    <AssemblyName>System.Windows.Forms</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Windows.Forms.DataGridViewCellCancelEventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>Fornisce dati per l'evento <see cref="E:System.Windows.Forms.DataGridView.DataError" />.</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 La gestione di <xref:System.Windows.Forms.DataGridView.DataError> evento consente di gestire le eccezioni generate dal codice all'esterno del controllo (ad esempio, un'origine dati esterna). Usare la <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Context%2A> proprietà per determinare lo stato del <xref:System.Windows.Forms.DataGridView> al momento dell'eccezione. Usare il <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A> proprietà da recuperare i dati dell'eccezione. Se si desidera gestire l'eccezione dai gestori di eventi aggiuntivi, impostare il <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A> proprietà `true`.  
  
 Il <xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex%2A> e <xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.RowIndex%2A> indicano in genere la cella in cui si è verificato l'errore nei dati. Quando si verifica l'errore in un'origine dati esterna, tuttavia, l'origine dati potrebbe non fornire la colonna in cui si è verificato l'errore. In questo caso, il <xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex%2A> proprietà indica in genere la colonna della cella corrente al momento dell'errore.  
  
   
  
## Examples  
 Esempio di codice seguente illustra come rispondere alle informazioni fornite dal <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs> classe. Questo esempio fa parte di un esempio più esaustivo disponibile nel <xref:System.Windows.Forms.DataGridViewComboBoxColumn> Cenni preliminari sulla classe.  
  
 [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CPP/employees.cpp#50)]
 [!code-csharp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CS/employees.cs#50)]
 [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/VB/employees.vb#50)]  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Windows.Forms.DataGridView" />
    <altmember cref="E:System.Windows.Forms.DataGridView.DataError" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public DataGridViewDataErrorEventArgs (Exception exception, int columnIndex, int rowIndex, System.Windows.Forms.DataGridViewDataErrorContexts context);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception, int32 columnIndex, int32 rowIndex, valuetype System.Windows.Forms.DataGridViewDataErrorContexts context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Windows.Forms.DataGridViewDataErrorEventArgs.#ctor(System.Exception,System.Int32,System.Int32,System.Windows.Forms.DataGridViewDataErrorContexts)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; DataGridViewDataErrorEventArgs(Exception ^ exception, int columnIndex, int rowIndex, System::Windows::Forms::DataGridViewDataErrorContexts context);" />
      <MemberSignature Language="F#" Value="new System.Windows.Forms.DataGridViewDataErrorEventArgs : Exception * int * int * System.Windows.Forms.DataGridViewDataErrorContexts -&gt; System.Windows.Forms.DataGridViewDataErrorEventArgs" Usage="new System.Windows.Forms.DataGridViewDataErrorEventArgs (exception, columnIndex, rowIndex, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Windows.Forms</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
        <Parameter Name="columnIndex" Type="System.Int32" />
        <Parameter Name="rowIndex" Type="System.Int32" />
        <Parameter Name="context" Type="System.Windows.Forms.DataGridViewDataErrorContexts" />
      </Parameters>
      <Docs>
        <param name="exception">Eccezione che si è verificata.</param>
        <param name="columnIndex">Indice di colonna della cella che ha generato l'evento <see cref="E:System.Windows.Forms.DataGridView.DataError" />.</param>
        <param name="rowIndex">Indice di riga della cella che ha generato l'evento <see cref="E:System.Windows.Forms.DataGridView.DataError" />.</param>
        <param name="context">Combinazione bit per bit dei valori di <see cref="T:System.Windows.Forms.DataGridViewDataErrorContexts" /> che indica il contesto in cui si è verificato l'errore.</param>
        <summary>Inizializza una nuova istanza della classe <see cref="T:System.Windows.Forms.DataGridViewDataErrorEventArgs" />.</summary>
        <remarks>To be added.</remarks>
        <altmember cref="T:System.Windows.Forms.DataGridView" />
        <altmember cref="E:System.Windows.Forms.DataGridView.DataError" />
      </Docs>
    </Member>
    <Member MemberName="Context">
      <MemberSignature Language="C#" Value="public System.Windows.Forms.DataGridViewDataErrorContexts Context { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance valuetype System.Windows.Forms.DataGridViewDataErrorContexts Context" />
      <MemberSignature Language="DocId" Value="P:System.Windows.Forms.DataGridViewDataErrorEventArgs.Context" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Context As DataGridViewDataErrorContexts" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property System::Windows::Forms::DataGridViewDataErrorContexts Context { System::Windows::Forms::DataGridViewDataErrorContexts get(); };" />
      <MemberSignature Language="F#" Value="member this.Context : System.Windows.Forms.DataGridViewDataErrorContexts" Usage="System.Windows.Forms.DataGridViewDataErrorEventArgs.Context" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Windows.Forms</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.DataGridViewDataErrorContexts</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Ottiene i dettagli sullo stato dell'oggetto <see cref="T:System.Windows.Forms.DataGridView" /> quando si è verificato l'errore.</summary>
        <value>Combinazione bit per bit dei valori di <see cref="T:System.Windows.Forms.DataGridViewDataErrorContexts" /> che specifica il contesto in cui si è verificato l'errore.</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 I membri del <xref:System.Windows.Forms.DataGridViewDataErrorContexts> enumerazione può essere combinato con i bit per bit `OR` operatore per rappresentare lo stato dell'associazione a dati <xref:System.Windows.Forms.DataGridView> quando si è verificato un errore nei dati. Ad esempio, se un utente immette un valore di cella non è valido (ad esempio, immettere un nome di una cella che richiede una data) e quindi seleziona una cella diversa, il <xref:System.Windows.Forms.DataGridView> proverà a eseguire il commit il valore della cella non è valido. Quando il commit ha esito negativo, il <xref:System.Windows.Forms.DataGridView> genererà un <xref:System.Windows.Forms.DataGridView.DataError> evento il cui <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Context%2A> proprietà avrà un valore <xref:System.Windows.Forms.DataGridViewDataErrorContexts.Commit> e <xref:System.Windows.Forms.DataGridViewDataErrorContexts.CurrentCellChange>.  
  
   
  
## Examples  
 Esempio di codice seguente viene illustrato come esaminare il contesto dell'errore. Questo esempio fa parte di un esempio più esaustivo disponibile nel <xref:System.Windows.Forms.DataGridViewComboBoxColumn> Cenni preliminari sulla classe.  
  
 [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CPP/employees.cpp#50)]
 [!code-csharp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CS/employees.cs#50)]
 [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/VB/employees.vb#50)]  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Windows.Forms.DataGridView" />
        <altmember cref="E:System.Windows.Forms.DataGridView.DataError" />
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Exception : Exception" Usage="System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Windows.Forms</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Ottiene l'eccezione che rappresenta l'errore.</summary>
        <value>Oggetto <see cref="T:System.Exception" /> che rappresenta l'errore.</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 Per gestire l'eccezione da più di un <xref:System.Windows.Forms.DataGridViewDataErrorEventHandler>, generare l'eccezione nuovamente alla fine di un gestore impostando il <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A> proprietà `true`.  
  
   
  
## Examples  
 Esempio di codice seguente viene illustrato come verificare il <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A> proprietà. Questo esempio fa parte di un esempio più esaustivo disponibile nel <xref:System.Windows.Forms.DataGridViewComboBoxColumn> Cenni preliminari sulla classe.  
  
 [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CPP/employees.cpp#50)]
 [!code-csharp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CS/employees.cs#50)]
 [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/VB/employees.vb#50)]  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Windows.Forms.DataGridView" />
        <altmember cref="E:System.Windows.Forms.DataGridView.DataError" />
      </Docs>
    </Member>
    <Member MemberName="ThrowException">
      <MemberSignature Language="C#" Value="public bool ThrowException { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance bool ThrowException" />
      <MemberSignature Language="DocId" Value="P:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException" />
      <MemberSignature Language="VB.NET" Value="Public Property ThrowException As Boolean" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property bool ThrowException { bool get(); void set(bool value); };" />
      <MemberSignature Language="F#" Value="member this.ThrowException : bool with get, set" Usage="System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Windows.Forms</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Boolean</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Ottiene o imposta un valore che indica se generare l'eccezione dopo che il delegato <see cref="T:System.Windows.Forms.DataGridViewDataErrorEventHandler" /> ne ha ultimata l'elaborazione.</summary>
        <value>
          <see langword="true" /> se l'eccezione deve essere generata; in caso contrario, <see langword="false" />. Il valore predefinito è <see langword="false" />.</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 Impostare questa proprietà su `false` se il <xref:System.Windows.Forms.DataGridViewDataErrorEventHandler> sono state esaminate con l'eccezione rappresentata dalle <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A> proprietà se non si desidera propagare l'eccezione a un altro <xref:System.Windows.Forms.DataGridViewDataErrorEventHandler> che può gestire il <xref:System.Windows.Forms.DataGridView.DataError> evento.  
  
 A scopo di debug, può essere utile propagare l'eccezione ed esaminare l'analisi dello stack per le informazioni relative al contesto dell'errore.  
  
   
  
## Examples  
 Esempio di codice seguente illustra l'uso di <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A> proprietà per indicare che non deve essere generata l'eccezione. Questo esempio fa parte di un esempio più esaustivo disponibile nel <xref:System.Windows.Forms.DataGridViewComboBoxColumn> Cenni preliminari sulla classe.  
  
 [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CPP/employees.cpp#50)]
 [!code-csharp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/CS/employees.cs#50)]
 [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees/VB/employees.vb#50)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentException">Durante l'impostazione di questa proprietà su <see langword="true" />, il valore della proprietà <see cref="P:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception" /> è <see langword="null" />.</exception>
        <altmember cref="T:System.Windows.Forms.DataGridView" />
        <altmember cref="E:System.Windows.Forms.DataGridView.DataError" />
      </Docs>
    </Member>
  </Members>
</Type>